### ISSUE TITLE
General site functionality

### ISSUE THREAD

**Issue by joshdavies14** [Joeyh021/SoftEng-Project#15]
- [x] Home page
- [x] FAQs
- [x] Privacy policy
- [x] App feedback form
- [x] General site base/theme (to be done partially pre-sprint by @joshdavies14

**Comment by NoahNok** [comment]
Have templated an FAQ design
Have templated a Feedback form design, still needs backend implementation though!

**Comment by NoahNok** [comment]
Still waiting on auth to be done, so I can properly link the feedback form, homepage will probably be populated by data from features added later on!

Privacy Policy can be properly added whenever!
