### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by joshdavies14** [Joeyh021/SoftEng-Project#61]
We haven't really been writing tests as we go so I'll write some functional tests this week using Cypress and pytest, once I work out how they work :P (among me going through all other work as it's completed xd)

**Comment by Joeyh021** [comment]
Can see examples of using pytest with authentication [here](https://github.com/Joeyh021/mentea/blob/54d92a8cecab5e33f4c42299aa1eaf1f16976280/people/test/plans_of_action_tests.py)

**Comment by Joeyh021** [comment]
- [x] Chat Tests
- [ ] Feedback Tests
- [x] Mentee Tests
- [x] Mentor Tests
- [x] Workshop Tests
- [x] Profile Tests
